theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/nous-logo.png'
    footer: ''
  home:
    head:
      title: site
  posts:
    index:
      layout: highlight
      options:
        author: true
        categories: true
        date: false
        image: true
        reading_time: false
        summary: false
        subtitle: false
        with_more: true
